language: node_js
before_script:
- npm install -g grunt-cli
- npm install -g mocha
node_js:
- 4.1.2
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_6de54f97b202_key -iv $encrypted_6de54f97b202_iv
  -in dokku-deploy.enc -out dokku-deploy -d
